language: rust
cache: cargo
sudo: false

os:
  - linux
  - osx
  - windows

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: stable
    - rust: beta
    - os: windows
  fast_finish: true
